version: 1
runtime: python27
api_version: 1
threadsafe: true
application: bookmybook-963

handlers:
- url: /q
  script: hello.app
- url: /q2
  script: hello2.app



default_expiration: "1d 12h"

libraries:
- name: lxml
  version: "2.3.5"